---
- hosts: all
  become: true
  tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: no
    vars:
      packages:
      - gnupg2
      #- mysql-server

  - name: Add current user with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: "{{ username }}"
      uid: 1001
      groups: users, wheel
      append: yes

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'